### ISSUE TITLE
[Documentation] Does it work with other background image setters or wallpapers?

### ISSUE THREAD

**Issue by rubyFeedback** [fusionhuh/deskimg#1]
Hey there.

I am using icewm right now. Icewm uses some default desktop I don't care about
but I also have some wallpapers I like.

My question is: could you add perhaps one paragraph for deskimg, to explain what
happens with other existing wallpapers? For instance, can wallpapers be in the
"background" and deskimg overlays things on top? Or is deskimg exclusive and 
will occupy all of the background. This would be nice to clear up and clarify in the
main README as-is. Thank you for reading this and perhaps considering it.

**Comment by fusionhuh** [comment]
hi there,

deskimg works by creating a transparent gtk window and then drawing the specified graphic inside of that window. because it is a window, it will always be on top of the wallpaper and should never cover the background unless you give it a non-transparent graphic with dimensions the size of your screen. let me know if i misinterpreted your question. i will also add some details to the README later today (hopefully).
